.github/actions/markdown-lint/action.yml, .github/workflows/ci_release.yml, .markdownlint.yaml, EXAMPLE_pull_request_template.md, README.md
This PR refactors the markdown-lint action into this repo and integrates it with this repo's CI. 
Now all other repos can use the same action.
=> .github: add markdown-lint action and remove scheduled run

.github/CODEOWNERS, .github/workflows/ci_release.yml, CONTRIBUTING.md
This PR creates an org level `CONTRIBUTING.md` doc. 
If there is no `CONTRIBUTING.md` doc in a repository, this one will be used.  
This is an initial draft that focuses on some key parts of our Github processes. In the future this doc can be expanded to contain more information around our engineering standards.
=> Celestia Contributing doc

.github/actions/markdown-lint/action.yml, .github/workflows/daily.yml, .github/workflows/reusable_stale.yml
This PR extends the `markdown-lint` action to include a link checker that the app was using.
It also brings in the stale PR checking action the app was using and adds a daily workflow to this repo that calls it as an example to other repos.
=> .github: update markdown-lint action to include link checker and add stale workflow

.github/workflows/reusable_dockerfile_pipeline.yml
Hello team!
Some context here.
Sometimes is possible that we have multiples `Dockerfiles` in the same repo (monorepo approach for example), and we have the need to specify a different package in our registry, this feature allow us to specify via github inputs the registry name where we'll publish the container.
ℹ️ **Keeping by default, the one that we were using before, the repository name.**
=> feat: Admit new input: packageName

.github/workflows/reusable_dockerfile_pipeline.yml
Bug report: https://github.com/celestiaorg/devops/issues/172
Hello!
There's an issue when building the containers using the matrix, it overrides the previous image in the registry... so we cannot use this approach.
Reverts https://github.com/celestiaorg/.github/pull/43
Thanks in advance!
closes: https://github.com/celestiaorg/devops/issues/172
=> fix: undo matrix

adr-template.md
There have been some deviations of ADRs across the org so we are creating the common template here for reference. As mentioned in #39 the individual repos could create a simple `Makefile` command to copy in the template when creating a new ADR.
Closes #39 
Related to https://github.com/celestiaorg/celestia-app/issues/1415
=> copy over adr template

.github/workflows/reusable_repository_dispatch.yml
This PR adds a reusable workflow for the repository dispatch trigger. I tested this workflow on my personal repos with simple echo statements. I'm almost positive that we will find some improvements to this workflow but we will only identify those by using it and trying to link our repo E2E testing. So for now I think this is the right place to start.
I've already added the necessary secrets to the celestia and rollkit orgs so we should be able to start testing.
=> Add repository dispatch reusable workflow

.github/workflows/reusable_testground_test.yaml
hello team!
This GitHub action, named "TestGround Tests", allows you to run tests on the TestGround platform for a specific set of files in your repository.
This PR contains a common pipeline to execute TestGround via Github Action 👀 
---
- It checks out the code from the repository.
- It clones the TestGround and test-infra repositories.
- `test-infra`: where we have the tests
- `testground`: build the testground tool
- It builds TestGround.
- It generates the TestGround configuration file for the specified region and TestGround LoadBalancer URL.
- If a specific commit SHA is provided for the Celestia node repository, it updates the `go.mod` file to use that specific commit instead of the current version.
- It plans the execution of the test.
- It starts the TestGround daemon service.
- …
=> feat: TestGround GA

.github/workflows/reusable_dockerfile_pipeline.yml
This PR changes two things:
- Build and push the amd64 container image, once finished build amd64 and arm64 and override previously pushed image
- Push amd64 images on each push (with sha tagged containers)
I tested it here:
- https://github.com/smuu/celestiaorg-celestia-node/actions?query=branch%3Afeature%2Fdecouple-arch-builds
- https://github.com/smuu/celestiaorg-celestia-node/actions?query=branch%3Av9.9.9
=> feat: speed up amd64 availability & push amd64 on each commit

.github/workflows/reusable_dockerfile_pipeline.yml
The docker workflow had a duplicate build and push step that was causing the CI to fail.
This should be applied/verified on rollkit and we should bump the version. 
This should close https://github.com/celestiaorg/devops/issues/326
=> Remove failing docker publish line

.github/workflows/reusable_dockerfile_pipeline.yml
hello team!
I've added the property `context` to the pipelines due to the issue that we're facing that we lose the `ldflags` values after building the container using GitHub.
I've done some different tests, and I realized that if we added this property, we would keep the values and won't need to add the `embed` files in the repos.
Some of the containers tested are:
https://github.com/jrmanes/celestia-node/pkgs/container/celestia-node
https://github.com/jrmanes/.github/commits/main/.github/workflows/reusable_dockerfile_pipeline.yml
---
Some images:
Without using `context` during build:
Using `context` during build:
---
*It will report only if it's in a tag, it's okay if we cannot see it, only with tags*
---
I hope this will fix the issue that we're facing atm
Thanks in advance!
Jose Ramon …
=> feat: use context - seems like it fixes the ldflags issue

.github/workflows/reusable_dockerfile_pipeline.yml
Reverts celestiaorg/.github#62
and fixes logic to properly address the issue.
=> Revert "Remove failing docker publish line"

.github/actions/markdown-lint/action.yml
Attempt to resolve https://github.com/celestiaorg/celestia-app/issues/2212 by upgrading markdownlint-cli to the latest release: [v0.35.0](https://github.com/igorshubovych/markdownlint-cli/releases/tag/v0.35.0)
cc: @SweeXordious
=> chore: upgrade to markdownlint-cli v0.35.0

.github/workflows/reusable_dockerfile_pipeline.yml
Noticed a bug when upgrading node. Not sure why it didn't get flagged when I tested it. 
There where unneeded `echo` statements that didn't have a closed parentheses.
=> bug: remove buggy echo statement

.github/workflows/reusable_dockerfile_pipeline.yml
logic was use `github.event` instead of `github.event_name` resulting in `build_for_pr` always being false.
=> bug: fix github.event_name error

.github/workflows/reusable_dockerfile_pipeline.yml
Turns out if you try and log an object that is too big the ci fails.
=> debug: remove echo statement for large object

.github/workflows/reusable_dockerfile_pipeline.yml
Here is the debug log:
The variables that we were creating were assumed boolean types because when printed they are `true` and `false`. However by checking the values against boolean and string representations, we can see that the variables are indeed strings. This resulted in the logical if statements always being evaluated to `true` because if a string is not `""` then it is true.
=> bug: fix handling of variables in conditions

.github/workflows/dockerfile_workflow_test.yaml, .gitignore, docker-action-test/Dockerfile, docker-action-test/go.mod, docker-action-test/main.go
=> feat: add a simple DockerFile and runner test

.github/workflows/dockerfile_workflow_test.yaml, .github/workflows/reusable_dockerfile_pipeline.yml
Closes #93 
This change skips running the dockerhub and scaleway runs when it is a PR. 
We use org level secrets for logging into dockerhub and scaleway, and these secretes are only accessible by native branches, or users with write access. 
This means that on PRs from forks or non team members, the runs would fail. 
These still pass on main on merge, because at that point, the permission issue is no longer present. 
Additional this change removes the appended hash to the action run, which causes issues with linking the action to the branch protection rules. 
Verified and tested: https://github.com/celestiaorg/.github/actions/runs/7790602743
=> fix: fix failing docker CI due to permission issues on PRs

.github/workflows/reusable_create_release_tracking_epic.yml, .github/workflows/reusable_release_tracking_epic.yml
Video overview: https://share.descript.com/view/dRemXmZK3Wz
=> feat(ci): add workflow for creating an EPIC issue for release tracking

.github/workflows/reusable_dockerfile_pipeline.yml
The logic check was producing a red x on push events to PRs when the build flags where both false. This PR updates the logic for this case to be a green check as this is an expected and acceptable case. 
This update then required an additional logic check added to the build stage to properly handle when the step should be running.
=> fix(ci): update logic check in reuseable pipeline

.github/workflows/reusable_create_release_tracking_epic.yml
=> chore(ci): update issue tasks for release epic

.github/workflows/reusable_dockerfile_pipeline.yml
Added a `checkout_ref` input to the dockerfile workflow. This would enable the calling repos to add a `workflow_dispatch` trigger and supply a specific ref (tag, branch, sha) to run the workflow against. The default is an empty string which tells the checkout action to use the ref of the calling event. 
REF: https://github.com/actions/checkout?tab=readme-ov-file#usage
=> feat: add checkout ref to support building from a specific ref manually

.github/workflows/reusable_dockerfile_pipeline.yml
resolves #113 
Example of empty tag on push event confirming no impact: https://github.com/celestiaorg/.github/actions/runs/11035460576/job/30651542020#step:5:15
Example of the tag being present: 
In the step: https://github.com/celestiaorg/.github/actions/runs/11035583857/job/30651974980#step:5:58
In the output: https://github.com/celestiaorg/.github/actions/runs/11035583857/job/30651974980#step:5:16
=> fix: add type=raw tag for workflow dispatch events to metadata step

.github/workflows/reusable_dockerfile_pipeline.yml
Trivy has been consistently failing due to rate limit. It current is running as info only so it wouldn't fail on error anyways. 
Commenting out until it can be implemented in a more reliable and useful way. 
Closes https://github.com/celestiaorg/.github/issues/115
=> chore(ci): comment out Trivy due to instability

.github/workflows/reusable_dockerfile_pipeline.yml
Closes https://github.com/celestiaorg/celestia-app/issues/4128
The celestia-app Docker images only supports amd64 and we think it is because the amd64 step completes first and publishes. Then the other step that builds an image that supports both amd64 and arm64 doesn't overwrite the exclusive amd64 image.
https://github.com/celestiaorg/celestia-app/issues/4128#issuecomment-2548358995 thanks @ramin 🫡
=> fix: remove separate amd64 publish step

.github/workflows/reusable_dockerfile_pipeline.yml
This PR adds support for specifying build args in the re-usable docker pipeline workflow.
I found myself needing to specify build args in a Dockerfile, right now it there is no way to specify these, I think an optional flag that defaults to an empty string (i.e. no build args) is the simplest way to achieve this.
Usage would look something like.
```yaml
docker-multiplexer-build:
permissions:
contents: write
packages: write
uses: celestiaorg/.github/.github/workflows/reusable_dockerfile_pipeline.yml@xxxxxxx
with:
dockerfile: docker/multiplexer.Dockerfile
checkout_ref: ${{ github.event.inputs.ref }}
packageName: celestia-app-multiplexer
buildArgs: |
TARGETOS=linux
TARGETARCH=amd64
secrets: inherit
```
=> feat: Support arbitrary build args in docker pipeline workflow

.github/workflows/reusable_dockerfile_pipeline.yml
I went down a bit of a rabbit hole trying to figure out why things weren't working as expected.
There were 2 issues.
1. docker-push-action.build-args expects a multiline string, e.g.
```
TARGETOS=linux
TARGETARCH=amd64
```
however when you pass a string like this to a workflow call, (even if using the correct multi line syntax ) it gets parsed as a single line string.
This PR parses that string and converts it into the correct format. The syntax is a bit weird, but it is what is shown in the [official docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#example-of-a-multiline-string).
2. The second issue I ran into was that the workflow was not being run on PRs.
there seems to be an issue with the conditional
`if: …
=> fix: correctly pass build arguments to docker build, build images on PRs

.github/workflows/reusable_dockerfile_pipeline.yml
Closes https://github.com/celestiaorg/.github/issues/131
We can't push Docker images on PRs from forks. IMO we could skip this entire workflow (not just one step) if this isn't a merge commit but this seems like the easiest way to address the regression.
cc: @chatton
=> fix: only build and push on merge

.github/workflows/reusable_dockerfile_pipeline.yml
A possible solution to https://github.com/celestiaorg/.github/issues/134
This PR modifies the existing workflow so that the ghcr images are built on PRs. And both dockerhub and ghcr images are built on merge.
Note: I don't think it is possible to purely depend on the `run-on-pr` field, as this would mean you have to hard code in true or false within the strategy matrix and would not be able to dynamically use a conditional (in this case `run`).
As a result of this I left `build_for_pr` and `build_for_merge` unchanged as they provide the correct information needed to determine if we should set `run`.
Tested on my fork https://github.com/chatton/celestia-app/actions/runs/14615820840/job/41003749579 and the images build from PRs.
=> fix: ensure images are built on PRs

CONTRIBUTING.md
Specifies that AI slop or farming PRs will be closed.
This way, we can all be on the same page which PRs should be reviewed, and which should be closed without explanations.
=> docs: add an external contribution guideline
